name: Checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: python3 -m pip install ".[test]"

      - name: Run tests
        env:
          WAGSTAILS_TEST_ENV: true
        run: python3 -m pytest tests/
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python3 -m pip install ".[dev]"

      - name: Check style
        run: python3 -m ruff check . && ruff format --check .
  precommit_hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python3 -m pip install ".[dev]"

      - name: Run pre-commit end-of-file-fixer hook
        run: pre-commit run end-of-file-fixer --all-files

      - name: Run pre-commit trailing-whitespace hook
        run: pre-commit run trailing-whitespace --all-files

      - name: Run pre-commit mixed-line-ending hook
        run: pre-commit run mixed-line-ending --all-files
  docs:
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.SPHINX_GITHUB_CHANGELOG_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[docs]'

      - name: Attempt docs build
        working-directory: ./docs
        run: make html
